//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.25 at 05:13:09 PM EDT 
//


package com.comp4601project.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MemberOfParliament" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PersonShortHonorific" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PersonOfficialFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="PersonOfficialLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ConstituencyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ConstituencyProvinceTerritoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CaucusShortName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="FromDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="ToDateTime">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="xsi:nil" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="xmlns:xsd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="xmlns:xsi" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "memberOfParliament"
})
@XmlRootElement(name = "MemberOfParliamentList")
public class MemberOfParliamentList {

    @XmlElement(name = "MemberOfParliament", required = true)
    protected List<MemberOfParliamentList.MemberOfParliament> memberOfParliament;
    @XmlAttribute(name = "xmlns:xsd")
    protected String xmlnsXsd;
    @XmlAttribute(name = "xmlns:xsi")
    protected String xmlnsXsi;

    /**
     * Gets the value of the memberOfParliament property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the memberOfParliament property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMemberOfParliament().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MemberOfParliamentList.MemberOfParliament }
     * 
     * 
     */
    public List<MemberOfParliamentList.MemberOfParliament> getMemberOfParliament() {
        if (memberOfParliament == null) {
            memberOfParliament = new ArrayList<MemberOfParliamentList.MemberOfParliament>();
        }
        return this.memberOfParliament;
    }

    /**
     * Gets the value of the xmlnsXsd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsXsd() {
        return xmlnsXsd;
    }

    /**
     * Sets the value of the xmlnsXsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsXsd(String value) {
        this.xmlnsXsd = value;
    }

    /**
     * Gets the value of the xmlnsXsi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsXsi() {
        return xmlnsXsi;
    }

    /**
     * Sets the value of the xmlnsXsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsXsi(String value) {
        this.xmlnsXsi = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PersonShortHonorific" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PersonOfficialFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="PersonOfficialLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ConstituencyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ConstituencyProvinceTerritoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CaucusShortName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="FromDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="ToDateTime">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="xsi:nil" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "personShortHonorific",
        "personOfficialFirstName",
        "personOfficialLastName",
        "constituencyName",
        "constituencyProvinceTerritoryName",
        "caucusShortName",
        "fromDateTime",
        "toDateTime"
    })
    public static class MemberOfParliament {

        @XmlElement(name = "PersonShortHonorific", required = true)
        protected String personShortHonorific;
        @XmlElement(name = "PersonOfficialFirstName", required = true)
        protected String personOfficialFirstName;
        @XmlElement(name = "PersonOfficialLastName", required = true)
        protected String personOfficialLastName;
        @XmlElement(name = "ConstituencyName", required = true)
        protected String constituencyName;
        @XmlElement(name = "ConstituencyProvinceTerritoryName", required = true)
        protected String constituencyProvinceTerritoryName;
        @XmlElement(name = "CaucusShortName", required = true)
        protected String caucusShortName;
        @XmlElement(name = "FromDateTime", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar fromDateTime;
        @XmlElement(name = "ToDateTime", required = true)
        protected MemberOfParliamentList.MemberOfParliament.ToDateTime toDateTime;

        /**
         * Gets the value of the personShortHonorific property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonShortHonorific() {
            return personShortHonorific;
        }

        /**
         * Sets the value of the personShortHonorific property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonShortHonorific(String value) {
            this.personShortHonorific = value;
        }

        /**
         * Gets the value of the personOfficialFirstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonOfficialFirstName() {
            return personOfficialFirstName;
        }

        /**
         * Sets the value of the personOfficialFirstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonOfficialFirstName(String value) {
            this.personOfficialFirstName = value;
        }

        /**
         * Gets the value of the personOfficialLastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonOfficialLastName() {
            return personOfficialLastName;
        }

        /**
         * Sets the value of the personOfficialLastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonOfficialLastName(String value) {
            this.personOfficialLastName = value;
        }

        /**
         * Gets the value of the constituencyName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConstituencyName() {
            return constituencyName;
        }

        /**
         * Sets the value of the constituencyName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConstituencyName(String value) {
            this.constituencyName = value;
        }

        /**
         * Gets the value of the constituencyProvinceTerritoryName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConstituencyProvinceTerritoryName() {
            return constituencyProvinceTerritoryName;
        }

        /**
         * Sets the value of the constituencyProvinceTerritoryName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConstituencyProvinceTerritoryName(String value) {
            this.constituencyProvinceTerritoryName = value;
        }

        /**
         * Gets the value of the caucusShortName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCaucusShortName() {
            return caucusShortName;
        }

        /**
         * Sets the value of the caucusShortName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCaucusShortName(String value) {
            this.caucusShortName = value;
        }

        /**
         * Gets the value of the fromDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFromDateTime() {
            return fromDateTime;
        }

        /**
         * Sets the value of the fromDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFromDateTime(XMLGregorianCalendar value) {
            this.fromDateTime = value;
        }

        /**
         * Gets the value of the toDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link MemberOfParliamentList.MemberOfParliament.ToDateTime }
         *     
         */
        public MemberOfParliamentList.MemberOfParliament.ToDateTime getToDateTime() {
            return toDateTime;
        }

        /**
         * Sets the value of the toDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link MemberOfParliamentList.MemberOfParliament.ToDateTime }
         *     
         */
        public void setToDateTime(MemberOfParliamentList.MemberOfParliament.ToDateTime value) {
            this.toDateTime = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="xsi:nil" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class ToDateTime {

            @XmlAttribute(name = "xsi:nil")
            protected String xsiNil;

            /**
             * Gets the value of the xsiNil property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getXsiNil() {
                return xsiNil;
            }

            /**
             * Sets the value of the xsiNil property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setXsiNil(String value) {
                this.xsiNil = value;
            }

        }

    }

}
