//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11-b140731.1112 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.26 at 03:17:46 PM EDT 
//


package com.comp4601project.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="voteParticipant" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="parliamentNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="sessionNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="decisionEventDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="decisionResultName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="decisionIsAgreedTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="decisionIsNegatived" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="decisionIsTied" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="decisionDivisionNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="decisionDivisionSubject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="decisionDivisionNumberOfYeas" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="decisionDivisionNumberOfNays" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="decisionDivisionNumberOfPaired" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="documentTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="billNumberCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="billLongTitle" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="billShortTitle" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="personOfficialFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="personOfficialLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="personShortHonorific" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="constituencyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="constituencyProvinceTerritoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="voteValueName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="isVoteYea" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="isVoteNay" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="isVotePaired" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="xmlns:xsd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="xmlns:xsi" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "voteParticipant"
})
@XmlRootElement(name = "memberVotes")
public class MemberVotes {

    @XmlElement(required = true)
    protected List<MemberVotes.VoteParticipant> voteParticipant;
    @XmlAttribute(name = "xmlns:xsd")
    protected String xmlnsXsd;
    @XmlAttribute(name = "xmlns:xsi")
    protected String xmlnsXsi;

    /**
     * Gets the value of the voteParticipant property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the voteParticipant property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVoteParticipant().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MemberVotes.VoteParticipant }
     * 
     * 
     */
    public List<MemberVotes.VoteParticipant> getVoteParticipant() {
        if (voteParticipant == null) {
            voteParticipant = new ArrayList<MemberVotes.VoteParticipant>();
        }
        return this.voteParticipant;
    }

    /**
     * Gets the value of the xmlnsXsd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsXsd() {
        return xmlnsXsd;
    }

    /**
     * Sets the value of the xmlnsXsd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsXsd(String value) {
        this.xmlnsXsd = value;
    }

    /**
     * Gets the value of the xmlnsXsi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlnsXsi() {
        return xmlnsXsi;
    }

    /**
     * Sets the value of the xmlnsXsi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlnsXsi(String value) {
        this.xmlnsXsi = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="parliamentNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="sessionNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="decisionEventDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="decisionResultName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="decisionIsAgreedTo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="decisionIsNegatived" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="decisionIsTied" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="decisionDivisionNumber" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="decisionDivisionSubject" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="decisionDivisionNumberOfYeas" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="decisionDivisionNumberOfNays" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="decisionDivisionNumberOfPaired" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="documentTypeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="billNumberCode" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="billLongTitle" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="billShortTitle" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="personOfficialFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="personOfficialLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="personShortHonorific" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="constituencyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="constituencyProvinceTerritoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="voteValueName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="isVoteYea" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="isVoteNay" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="isVotePaired" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parliamentNumber",
        "sessionNumber",
        "decisionEventDateTime",
        "decisionResultName",
        "decisionIsAgreedTo",
        "decisionIsNegatived",
        "decisionIsTied",
        "decisionDivisionNumber",
        "decisionDivisionSubject",
        "decisionDivisionNumberOfYeas",
        "decisionDivisionNumberOfNays",
        "decisionDivisionNumberOfPaired",
        "documentTypeName",
        "billNumberCode",
        "billLongTitle",
        "billShortTitle",
        "personOfficialFirstName",
        "personOfficialLastName",
        "personShortHonorific",
        "constituencyName",
        "constituencyProvinceTerritoryName",
        "voteValueName",
        "isVoteYea",
        "isVoteNay",
        "isVotePaired"
    })
    public static class VoteParticipant {

        protected int parliamentNumber;
        protected int sessionNumber;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar decisionEventDateTime;
        @XmlElement(required = true)
        protected String decisionResultName;
        @XmlElement(required = true)
        protected String decisionIsAgreedTo;
        @XmlElement(required = true)
        protected String decisionIsNegatived;
        @XmlElement(required = true)
        protected String decisionIsTied;
        protected int decisionDivisionNumber;
        @XmlElement(required = true)
        protected String decisionDivisionSubject;
        protected int decisionDivisionNumberOfYeas;
        protected int decisionDivisionNumberOfNays;
        protected int decisionDivisionNumberOfPaired;
        @XmlElement(required = true)
        protected String documentTypeName;
        @XmlElement(required = true)
        protected Object billNumberCode;
        @XmlElement(required = true)
        protected Object billLongTitle;
        @XmlElement(required = true)
        protected Object billShortTitle;
        @XmlElement(required = true)
        protected String personOfficialFirstName;
        @XmlElement(required = true)
        protected String personOfficialLastName;
        @XmlElement(required = true)
        protected Object personShortHonorific;
        @XmlElement(required = true)
        protected String constituencyName;
        @XmlElement(required = true)
        protected String constituencyProvinceTerritoryName;
        @XmlElement(required = true)
        protected String voteValueName;
        @XmlElement(required = true)
        protected String isVoteYea;
        @XmlElement(required = true)
        protected String isVoteNay;
        @XmlElement(required = true)
        protected String isVotePaired;

        /**
         * Gets the value of the parliamentNumber property.
         * 
         */
        public int getParliamentNumber() {
            return parliamentNumber;
        }

        /**
         * Sets the value of the parliamentNumber property.
         * 
         */
        public void setParliamentNumber(int value) {
            this.parliamentNumber = value;
        }

        /**
         * Gets the value of the sessionNumber property.
         * 
         */
        public int getSessionNumber() {
            return sessionNumber;
        }

        /**
         * Sets the value of the sessionNumber property.
         * 
         */
        public void setSessionNumber(int value) {
            this.sessionNumber = value;
        }

        /**
         * Gets the value of the decisionEventDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDecisionEventDateTime() {
            return decisionEventDateTime;
        }

        /**
         * Sets the value of the decisionEventDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDecisionEventDateTime(XMLGregorianCalendar value) {
            this.decisionEventDateTime = value;
        }

        /**
         * Gets the value of the decisionResultName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDecisionResultName() {
            return decisionResultName;
        }

        /**
         * Sets the value of the decisionResultName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDecisionResultName(String value) {
            this.decisionResultName = value;
        }

        /**
         * Gets the value of the decisionIsAgreedTo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDecisionIsAgreedTo() {
            return decisionIsAgreedTo;
        }

        /**
         * Sets the value of the decisionIsAgreedTo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDecisionIsAgreedTo(String value) {
            this.decisionIsAgreedTo = value;
        }

        /**
         * Gets the value of the decisionIsNegatived property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDecisionIsNegatived() {
            return decisionIsNegatived;
        }

        /**
         * Sets the value of the decisionIsNegatived property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDecisionIsNegatived(String value) {
            this.decisionIsNegatived = value;
        }

        /**
         * Gets the value of the decisionIsTied property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDecisionIsTied() {
            return decisionIsTied;
        }

        /**
         * Sets the value of the decisionIsTied property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDecisionIsTied(String value) {
            this.decisionIsTied = value;
        }

        /**
         * Gets the value of the decisionDivisionNumber property.
         * 
         */
        public int getDecisionDivisionNumber() {
            return decisionDivisionNumber;
        }

        /**
         * Sets the value of the decisionDivisionNumber property.
         * 
         */
        public void setDecisionDivisionNumber(int value) {
            this.decisionDivisionNumber = value;
        }

        /**
         * Gets the value of the decisionDivisionSubject property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDecisionDivisionSubject() {
            return decisionDivisionSubject;
        }

        /**
         * Sets the value of the decisionDivisionSubject property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDecisionDivisionSubject(String value) {
            this.decisionDivisionSubject = value;
        }

        /**
         * Gets the value of the decisionDivisionNumberOfYeas property.
         * 
         */
        public int getDecisionDivisionNumberOfYeas() {
            return decisionDivisionNumberOfYeas;
        }

        /**
         * Sets the value of the decisionDivisionNumberOfYeas property.
         * 
         */
        public void setDecisionDivisionNumberOfYeas(int value) {
            this.decisionDivisionNumberOfYeas = value;
        }

        /**
         * Gets the value of the decisionDivisionNumberOfNays property.
         * 
         */
        public int getDecisionDivisionNumberOfNays() {
            return decisionDivisionNumberOfNays;
        }

        /**
         * Sets the value of the decisionDivisionNumberOfNays property.
         * 
         */
        public void setDecisionDivisionNumberOfNays(int value) {
            this.decisionDivisionNumberOfNays = value;
        }

        /**
         * Gets the value of the decisionDivisionNumberOfPaired property.
         * 
         */
        public int getDecisionDivisionNumberOfPaired() {
            return decisionDivisionNumberOfPaired;
        }

        /**
         * Sets the value of the decisionDivisionNumberOfPaired property.
         * 
         */
        public void setDecisionDivisionNumberOfPaired(int value) {
            this.decisionDivisionNumberOfPaired = value;
        }

        /**
         * Gets the value of the documentTypeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDocumentTypeName() {
            return documentTypeName;
        }

        /**
         * Sets the value of the documentTypeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDocumentTypeName(String value) {
            this.documentTypeName = value;
        }

        /**
         * Gets the value of the billNumberCode property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getBillNumberCode() {
            return billNumberCode;
        }

        /**
         * Sets the value of the billNumberCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setBillNumberCode(Object value) {
            this.billNumberCode = value;
        }

        /**
         * Gets the value of the billLongTitle property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getBillLongTitle() {
            return billLongTitle;
        }

        /**
         * Sets the value of the billLongTitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setBillLongTitle(Object value) {
            this.billLongTitle = value;
        }

        /**
         * Gets the value of the billShortTitle property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getBillShortTitle() {
            return billShortTitle;
        }

        /**
         * Sets the value of the billShortTitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setBillShortTitle(Object value) {
            this.billShortTitle = value;
        }

        /**
         * Gets the value of the personOfficialFirstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonOfficialFirstName() {
            return personOfficialFirstName;
        }

        /**
         * Sets the value of the personOfficialFirstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonOfficialFirstName(String value) {
            this.personOfficialFirstName = value;
        }

        /**
         * Gets the value of the personOfficialLastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonOfficialLastName() {
            return personOfficialLastName;
        }

        /**
         * Sets the value of the personOfficialLastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonOfficialLastName(String value) {
            this.personOfficialLastName = value;
        }

        /**
         * Gets the value of the personShortHonorific property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getPersonShortHonorific() {
            return personShortHonorific;
        }

        /**
         * Sets the value of the personShortHonorific property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setPersonShortHonorific(Object value) {
            this.personShortHonorific = value;
        }

        /**
         * Gets the value of the constituencyName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConstituencyName() {
            return constituencyName;
        }

        /**
         * Sets the value of the constituencyName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConstituencyName(String value) {
            this.constituencyName = value;
        }

        /**
         * Gets the value of the constituencyProvinceTerritoryName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConstituencyProvinceTerritoryName() {
            return constituencyProvinceTerritoryName;
        }

        /**
         * Sets the value of the constituencyProvinceTerritoryName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConstituencyProvinceTerritoryName(String value) {
            this.constituencyProvinceTerritoryName = value;
        }

        /**
         * Gets the value of the voteValueName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getVoteValueName() {
            return voteValueName;
        }

        /**
         * Sets the value of the voteValueName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setVoteValueName(String value) {
            this.voteValueName = value;
        }

        /**
         * Gets the value of the isVoteYea property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsVoteYea() {
            return isVoteYea;
        }

        /**
         * Sets the value of the isVoteYea property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsVoteYea(String value) {
            this.isVoteYea = value;
        }

        /**
         * Gets the value of the isVoteNay property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsVoteNay() {
            return isVoteNay;
        }

        /**
         * Sets the value of the isVoteNay property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsVoteNay(String value) {
            this.isVoteNay = value;
        }

        /**
         * Gets the value of the isVotePaired property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIsVotePaired() {
            return isVotePaired;
        }

        /**
         * Sets the value of the isVotePaired property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIsVotePaired(String value) {
            this.isVotePaired = value;
        }

    }

}
