//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11-b140731.1112 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.26 at 03:17:35 PM EDT 
//


package com.comp4601project.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="memberOfParliament" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="personShortHonorific" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="personOfficialFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="personOfficialLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="constituencyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="constituencyProvinceTerritoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="caucusShortName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fromDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="toDateTime">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="xsi:nil" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="xmlns:xsd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="xmlns:xsi" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "memberOfParliament"
})
@XmlRootElement(name = "list")
public class MemberOfParliamentList {

    @XmlElement(required = true)
    protected List<MemberOfParliamentList.MemberOfParliament> memberOfParliament;


    /**
     * Gets the value of the memberOfParliament property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the memberOfParliament property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMemberOfParliament().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MemberOfParliamentList.MemberOfParliament }
     * 
     * 
     */
    public List<MemberOfParliamentList.MemberOfParliament> getMemberOfParliament() {
        if (memberOfParliament == null) {
            memberOfParliament = new ArrayList<MemberOfParliamentList.MemberOfParliament>();
        }
        return this.memberOfParliament;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="personShortHonorific" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="personOfficialFirstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="personOfficialLastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="constituencyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="constituencyProvinceTerritoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="caucusShortName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fromDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="toDateTime">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="xsi:nil" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "personShortHonorific",
        "personOfficialFirstName",
        "personOfficialLastName",
        "constituencyName",
        "constituencyProvinceTerritoryName",
        "caucusShortName",
        "fromDateTime"
    })
    public static class MemberOfParliament {

        @XmlElement(required = true)
        protected String personShortHonorific;
        @XmlElement(required = true)
        protected String personOfficialFirstName;
        @XmlElement(required = true)
        protected String personOfficialLastName;
        @XmlElement(required = true)
        protected String constituencyName;
        @XmlElement(required = true)
        protected String constituencyProvinceTerritoryName;
        @XmlElement(required = true)
        protected String caucusShortName;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar fromDateTime;

        /**
         * Gets the value of the personShortHonorific property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonShortHonorific() {
            return personShortHonorific;
        }

        /**
         * Sets the value of the personShortHonorific property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonShortHonorific(String value) {
            this.personShortHonorific = value;
        }

        /**
         * Gets the value of the personOfficialFirstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonOfficialFirstName() {
            return personOfficialFirstName;
        }

        /**
         * Sets the value of the personOfficialFirstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonOfficialFirstName(String value) {
            this.personOfficialFirstName = value;
        }

        /**
         * Gets the value of the personOfficialLastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPersonOfficialLastName() {
            return personOfficialLastName;
        }

        /**
         * Sets the value of the personOfficialLastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPersonOfficialLastName(String value) {
            this.personOfficialLastName = value;
        }

        /**
         * Gets the value of the constituencyName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConstituencyName() {
            return constituencyName;
        }

        /**
         * Sets the value of the constituencyName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConstituencyName(String value) {
            this.constituencyName = value;
        }

        /**
         * Gets the value of the constituencyProvinceTerritoryName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConstituencyProvinceTerritoryName() {
            return constituencyProvinceTerritoryName;
        }

        /**
         * Sets the value of the constituencyProvinceTerritoryName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConstituencyProvinceTerritoryName(String value) {
            this.constituencyProvinceTerritoryName = value;
        }

        /**
         * Gets the value of the caucusShortName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCaucusShortName() {
            return caucusShortName;
        }

        /**
         * Sets the value of the caucusShortName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCaucusShortName(String value) {
            this.caucusShortName = value;
        }

        /**
         * Gets the value of the fromDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFromDateTime() {
            return fromDateTime;
        }

        /**
         * Sets the value of the fromDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFromDateTime(XMLGregorianCalendar value) {
            this.fromDateTime = value;
        }




        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="xsi:nil" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class ToDateTime {

            @XmlAttribute(name = "xsi:nil")
            protected String xsiNil;

            /**
             * Gets the value of the xsiNil property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getXsiNil() {
                return xsiNil;
            }

            /**
             * Sets the value of the xsiNil property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setXsiNil(String value) {
                this.xsiNil = value;
            }

        }

    }

}
