//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11-b140731.1112 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.26 at 04:56:45 PM EDT 
//


package com.comp4601project.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.comp4601project.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.comp4601project.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Bill }
     * 
     */
    public Bill createBill() {
        return new Bill();
    }

    /**
     * Create an instance of {@link Bill.Events }
     * 
     */
    public Bill.Events createBillEvents() {
        return new Bill.Events();
    }

    /**
     * Create an instance of {@link Bill.Events.LegislativeEvents }
     * 
     */
    public Bill.Events.LegislativeEvents createBillEventsLegislativeEvents() {
        return new Bill.Events.LegislativeEvents();
    }

    /**
     * Create an instance of {@link Bill.Events.LegislativeEvents.Event }
     * 
     */
    public Bill.Events.LegislativeEvents.Event createBillEventsLegislativeEventsEvent() {
        return new Bill.Events.LegislativeEvents.Event();
    }

    /**
     * Create an instance of {@link Bill.Events.LegislativeEvents.Event.Status }
     * 
     */
    public Bill.Events.LegislativeEvents.Event.Status createBillEventsLegislativeEventsEventStatus() {
        return new Bill.Events.LegislativeEvents.Event.Status();
    }

    /**
     * Create an instance of {@link Bill.Events.LastMajorStageEvent }
     * 
     */
    public Bill.Events.LastMajorStageEvent createBillEventsLastMajorStageEvent() {
        return new Bill.Events.LastMajorStageEvent();
    }

    /**
     * Create an instance of {@link Bill.Events.LastMajorStageEvent.Event }
     * 
     */
    public Bill.Events.LastMajorStageEvent.Event createBillEventsLastMajorStageEventEvent() {
        return new Bill.Events.LastMajorStageEvent.Event();
    }

    /**
     * Create an instance of {@link Bill.Events.LastMajorStageEvent.Event.Status }
     * 
     */
    public Bill.Events.LastMajorStageEvent.Event.Status createBillEventsLastMajorStageEventEventStatus() {
        return new Bill.Events.LastMajorStageEvent.Event.Status();
    }

    /**
     * Create an instance of {@link Bill.Publications }
     * 
     */
    public Bill.Publications createBillPublications() {
        return new Bill.Publications();
    }

    /**
     * Create an instance of {@link Bill.Publications.Publication }
     * 
     */
    public Bill.Publications.Publication createBillPublicationsPublication() {
        return new Bill.Publications.Publication();
    }

    /**
     * Create an instance of {@link Bill.Publications.Publication.PublicationFiles }
     * 
     */
    public Bill.Publications.Publication.PublicationFiles createBillPublicationsPublicationPublicationFiles() {
        return new Bill.Publications.Publication.PublicationFiles();
    }

    /**
     * Create an instance of {@link Bill.PrimeMinister }
     * 
     */
    public Bill.PrimeMinister createBillPrimeMinister() {
        return new Bill.PrimeMinister();
    }

    /**
     * Create an instance of {@link Bill.PrimeMinister.PoliticalParty }
     * 
     */
    public Bill.PrimeMinister.PoliticalParty createBillPrimeMinisterPoliticalParty() {
        return new Bill.PrimeMinister.PoliticalParty();
    }

    /**
     * Create an instance of {@link Bill.PrimeMinister.PoliticalParty.Abbreviation }
     * 
     */
    public Bill.PrimeMinister.PoliticalParty.Abbreviation createBillPrimeMinisterPoliticalPartyAbbreviation() {
        return new Bill.PrimeMinister.PoliticalParty.Abbreviation();
    }

    /**
     * Create an instance of {@link Bill.LegisInfoNotes }
     * 
     */
    public Bill.LegisInfoNotes createBillLegisInfoNotes() {
        return new Bill.LegisInfoNotes();
    }

    /**
     * Create an instance of {@link Bill.ComingIntoForce }
     * 
     */
    public Bill.ComingIntoForce createBillComingIntoForce() {
        return new Bill.ComingIntoForce();
    }

    /**
     * Create an instance of {@link Bill.ComingIntoForce.Information }
     * 
     */
    public Bill.ComingIntoForce.Information createBillComingIntoForceInformation() {
        return new Bill.ComingIntoForce.Information();
    }

    /**
     * Create an instance of {@link Bill.SponsorAffiliation }
     * 
     */
    public Bill.SponsorAffiliation createBillSponsorAffiliation() {
        return new Bill.SponsorAffiliation();
    }

    /**
     * Create an instance of {@link Bill.SponsorAffiliation.PoliticalParty }
     * 
     */
    public Bill.SponsorAffiliation.PoliticalParty createBillSponsorAffiliationPoliticalParty() {
        return new Bill.SponsorAffiliation.PoliticalParty();
    }

    /**
     * Create an instance of {@link Bill.SponsorAffiliation.PoliticalParty.Abbreviation }
     * 
     */
    public Bill.SponsorAffiliation.PoliticalParty.Abbreviation createBillSponsorAffiliationPoliticalPartyAbbreviation() {
        return new Bill.SponsorAffiliation.PoliticalParty.Abbreviation();
    }

    /**
     * Create an instance of {@link Bill.BillType }
     * 
     */
    public Bill.BillType createBillBillType() {
        return new Bill.BillType();
    }

    /**
     * Create an instance of {@link Bill.ShortTitle }
     * 
     */
    public Bill.ShortTitle createBillShortTitle() {
        return new Bill.ShortTitle();
    }

    /**
     * Create an instance of {@link Bill.BillTitle }
     * 
     */
    public Bill.BillTitle createBillBillTitle() {
        return new Bill.BillTitle();
    }

    /**
     * Create an instance of {@link Bill.ParliamentSession }
     * 
     */
    public Bill.ParliamentSession createBillParliamentSession() {
        return new Bill.ParliamentSession();
    }

    /**
     * Create an instance of {@link Bill.BillNumber }
     * 
     */
    public Bill.BillNumber createBillBillNumber() {
        return new Bill.BillNumber();
    }

    /**
     * Create an instance of {@link Bill.Statute }
     * 
     */
    public Bill.Statute createBillStatute() {
        return new Bill.Statute();
    }

    /**
     * Create an instance of {@link Bill.Events.LegislativeEvents.Event.Status.Title }
     * 
     */
    public Bill.Events.LegislativeEvents.Event.Status.Title createBillEventsLegislativeEventsEventStatusTitle() {
        return new Bill.Events.LegislativeEvents.Event.Status.Title();
    }

    /**
     * Create an instance of {@link Bill.Events.LastMajorStageEvent.Event.Status.Title }
     * 
     */
    public Bill.Events.LastMajorStageEvent.Event.Status.Title createBillEventsLastMajorStageEventEventStatusTitle() {
        return new Bill.Events.LastMajorStageEvent.Event.Status.Title();
    }

    /**
     * Create an instance of {@link Bill.Publications.Publication.Title }
     * 
     */
    public Bill.Publications.Publication.Title createBillPublicationsPublicationTitle() {
        return new Bill.Publications.Publication.Title();
    }

    /**
     * Create an instance of {@link Bill.Publications.Publication.PublicationFiles.PublicationFile }
     * 
     */
    public Bill.Publications.Publication.PublicationFiles.PublicationFile createBillPublicationsPublicationPublicationFilesPublicationFile() {
        return new Bill.Publications.Publication.PublicationFiles.PublicationFile();
    }

    /**
     * Create an instance of {@link Bill.PrimeMinister.Title }
     * 
     */
    public Bill.PrimeMinister.Title createBillPrimeMinisterTitle() {
        return new Bill.PrimeMinister.Title();
    }

    /**
     * Create an instance of {@link Bill.PrimeMinister.Person }
     * 
     */
    public Bill.PrimeMinister.Person createBillPrimeMinisterPerson() {
        return new Bill.PrimeMinister.Person();
    }

    /**
     * Create an instance of {@link Bill.PrimeMinister.PoliticalParty.Title }
     * 
     */
    public Bill.PrimeMinister.PoliticalParty.Title createBillPrimeMinisterPoliticalPartyTitle() {
        return new Bill.PrimeMinister.PoliticalParty.Title();
    }

    /**
     * Create an instance of {@link Bill.PrimeMinister.PoliticalParty.Abbreviation.Title }
     * 
     */
    public Bill.PrimeMinister.PoliticalParty.Abbreviation.Title createBillPrimeMinisterPoliticalPartyAbbreviationTitle() {
        return new Bill.PrimeMinister.PoliticalParty.Abbreviation.Title();
    }

    /**
     * Create an instance of {@link Bill.LegisInfoNotes.Title }
     * 
     */
    public Bill.LegisInfoNotes.Title createBillLegisInfoNotesTitle() {
        return new Bill.LegisInfoNotes.Title();
    }

    /**
     * Create an instance of {@link Bill.ComingIntoForce.Information.Title }
     * 
     */
    public Bill.ComingIntoForce.Information.Title createBillComingIntoForceInformationTitle() {
        return new Bill.ComingIntoForce.Information.Title();
    }

    /**
     * Create an instance of {@link Bill.SponsorAffiliation.Title }
     * 
     */
    public Bill.SponsorAffiliation.Title createBillSponsorAffiliationTitle() {
        return new Bill.SponsorAffiliation.Title();
    }

    /**
     * Create an instance of {@link Bill.SponsorAffiliation.Person }
     * 
     */
    public Bill.SponsorAffiliation.Person createBillSponsorAffiliationPerson() {
        return new Bill.SponsorAffiliation.Person();
    }

    /**
     * Create an instance of {@link Bill.SponsorAffiliation.PoliticalParty.Title }
     * 
     */
    public Bill.SponsorAffiliation.PoliticalParty.Title createBillSponsorAffiliationPoliticalPartyTitle() {
        return new Bill.SponsorAffiliation.PoliticalParty.Title();
    }

    /**
     * Create an instance of {@link Bill.SponsorAffiliation.PoliticalParty.Abbreviation.Title }
     * 
     */
    public Bill.SponsorAffiliation.PoliticalParty.Abbreviation.Title createBillSponsorAffiliationPoliticalPartyAbbreviationTitle() {
        return new Bill.SponsorAffiliation.PoliticalParty.Abbreviation.Title();
    }

    /**
     * Create an instance of {@link Bill.BillType.Title }
     * 
     */
    public Bill.BillType.Title createBillBillTypeTitle() {
        return new Bill.BillType.Title();
    }

    /**
     * Create an instance of {@link Bill.ShortTitle.Title }
     * 
     */
    public Bill.ShortTitle.Title createBillShortTitleTitle() {
        return new Bill.ShortTitle.Title();
    }

    /**
     * Create an instance of {@link Bill.BillTitle.Title }
     * 
     */
    public Bill.BillTitle.Title createBillBillTitleTitle() {
        return new Bill.BillTitle.Title();
    }

}
