//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11-b140731.1112 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.03 at 04:02:45 PM EDT 
//


package com.comp4601project.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.comp4601project.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentIntervention_QNAME = new QName("", "Intervention");
    private final static QName _HansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentFloorLanguage_QNAME = new QName("", "FloorLanguage");
    private final static QName _HansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentParaText_QNAME = new QName("", "ParaText");
    private final static QName _HansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentTimestamp_QNAME = new QName("", "Timestamp");
    private final static QName _HansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentProceduralText_QNAME = new QName("", "ProceduralText");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.comp4601project.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Hansard }
     * 
     */
    public Hansard createHansard() {
        return new Hansard();
    }

    /**
     * Create an instance of {@link Hansard.HansardBody }
     * 
     */
    public Hansard.HansardBody createHansardHansardBody() {
        return new Hansard.HansardBody();
    }

    /**
     * Create an instance of {@link Hansard.HansardBody.OrderOfBusiness }
     * 
     */
    public Hansard.HansardBody.OrderOfBusiness createHansardHansardBodyOrderOfBusiness() {
        return new Hansard.HansardBody.OrderOfBusiness();
    }

    /**
     * Create an instance of {@link Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness }
     * 
     */
    public Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness createHansardHansardBodyOrderOfBusinessSubjectOfBusiness() {
        return new Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness();
    }

    /**
     * Create an instance of {@link Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent }
     * 
     */
    public Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent createHansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContent() {
        return new Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent();
    }

    /**
     * Create an instance of {@link Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention }
     * 
     */
    public Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention createHansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentIntervention() {
        return new Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention();
    }

    /**
     * Create an instance of {@link Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention.Content }
     * 
     */
    public Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention.Content createHansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentInterventionContent() {
        return new Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention.Content();
    }

    /**
     * Create an instance of {@link Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention.PersonSpeaking }
     * 
     */
    public Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention.PersonSpeaking createHansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentInterventionPersonSpeaking() {
        return new Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention.PersonSpeaking();
    }

    /**
     * Create an instance of {@link Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.ParaText }
     * 
     */
    public Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.ParaText createHansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentParaText() {
        return new Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.ParaText();
    }

    /**
     * Create an instance of {@link Hansard.HansardBody.Intro }
     * 
     */
    public Hansard.HansardBody.Intro createHansardHansardBodyIntro() {
        return new Hansard.HansardBody.Intro();
    }

    /**
     * Create an instance of {@link Hansard.ExtractedInformation }
     * 
     */
    public Hansard.ExtractedInformation createHansardExtractedInformation() {
        return new Hansard.ExtractedInformation();
    }

    /**
     * Create an instance of {@link Hansard.DocumentTitle }
     * 
     */
    public Hansard.DocumentTitle createHansardDocumentTitle() {
        return new Hansard.DocumentTitle();
    }

    /**
     * Create an instance of {@link Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.Timestamp }
     * 
     */
    public Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.Timestamp createHansardHansardBodyOrderOfBusinessSubjectOfBusinessTimestamp() {
        return new Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.Timestamp();
    }

    /**
     * Create an instance of {@link Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.FloorLanguage }
     * 
     */
    public Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.FloorLanguage createHansardHansardBodyOrderOfBusinessSubjectOfBusinessFloorLanguage() {
        return new Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.FloorLanguage();
    }

    /**
     * Create an instance of {@link Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.ProceduralText }
     * 
     */
    public Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.ProceduralText createHansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentProceduralText() {
        return new Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.ProceduralText();
    }

    /**
     * Create an instance of {@link Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Timestamp }
     * 
     */
    public Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Timestamp createHansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentTimestamp() {
        return new Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Timestamp();
    }

    /**
     * Create an instance of {@link Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.FloorLanguage }
     * 
     */
    public Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.FloorLanguage createHansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentFloorLanguage() {
        return new Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.FloorLanguage();
    }

    /**
     * Create an instance of {@link Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention.Content.ParaText }
     * 
     */
    public Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention.Content.ParaText createHansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentInterventionContentParaText() {
        return new Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention.Content.ParaText();
    }

    /**
     * Create an instance of {@link Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention.PersonSpeaking.Affiliation }
     * 
     */
    public Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention.PersonSpeaking.Affiliation createHansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentInterventionPersonSpeakingAffiliation() {
        return new Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention.PersonSpeaking.Affiliation();
    }

    /**
     * Create an instance of {@link Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.ParaText.Document }
     * 
     */
    public Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.ParaText.Document createHansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentParaTextDocument() {
        return new Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.ParaText.Document();
    }

    /**
     * Create an instance of {@link Hansard.HansardBody.Intro.ParaText }
     * 
     */
    public Hansard.HansardBody.Intro.ParaText createHansardHansardBodyIntroParaText() {
        return new Hansard.HansardBody.Intro.ParaText();
    }

    /**
     * Create an instance of {@link Hansard.ExtractedInformation.ExtractedItem }
     * 
     */
    public Hansard.ExtractedInformation.ExtractedItem createHansardExtractedInformationExtractedItem() {
        return new Hansard.ExtractedInformation.ExtractedItem();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Intervention", scope = Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.class)
    public JAXBElement<Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention> createHansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentIntervention(Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention value) {
        return new JAXBElement<Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention>(_HansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentIntervention_QNAME, Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Intervention.class, Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.FloorLanguage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FloorLanguage", scope = Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.class)
    public JAXBElement<Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.FloorLanguage> createHansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentFloorLanguage(Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.FloorLanguage value) {
        return new JAXBElement<Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.FloorLanguage>(_HansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentFloorLanguage_QNAME, Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.FloorLanguage.class, Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.ParaText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ParaText", scope = Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.class)
    public JAXBElement<Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.ParaText> createHansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentParaText(Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.ParaText value) {
        return new JAXBElement<Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.ParaText>(_HansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentParaText_QNAME, Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.ParaText.class, Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Timestamp }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Timestamp", scope = Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.class)
    public JAXBElement<Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Timestamp> createHansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentTimestamp(Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Timestamp value) {
        return new JAXBElement<Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Timestamp>(_HansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentTimestamp_QNAME, Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.Timestamp.class, Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.ProceduralText }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProceduralText", scope = Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.class)
    public JAXBElement<Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.ProceduralText> createHansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentProceduralText(Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.ProceduralText value) {
        return new JAXBElement<Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.ProceduralText>(_HansardHansardBodyOrderOfBusinessSubjectOfBusinessSubjectOfBusinessContentProceduralText_QNAME, Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.ProceduralText.class, Hansard.HansardBody.OrderOfBusiness.SubjectOfBusiness.SubjectOfBusinessContent.class, value);
    }

}
