//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11-b140731.1112 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.26 at 03:18:08 PM EDT 
//


package com.comp4601project.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="vote" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="decision" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="relatedBill">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="totalYeas" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="totalNays" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="totalPaired" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="parliament" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="session" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="sitting" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="schemaVersion" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="parliament" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="session" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="sitting" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="votesRespecting" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fromDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="toDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="yea" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nay" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="paired" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vote"
})
@XmlRootElement(name = "votes")
public class Votes {

    @XmlElement(required = true)
    protected List<Votes.Vote> vote;
    @XmlAttribute(name = "schemaVersion")
    protected Integer schemaVersion;
    @XmlAttribute(name = "parliament")
    protected Integer parliament;
    @XmlAttribute(name = "session")
    protected Integer session;
    @XmlAttribute(name = "sitting")
    protected String sitting;
    @XmlAttribute(name = "votesRespecting")
    protected String votesRespecting;
    @XmlAttribute(name = "fromDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fromDate;
    @XmlAttribute(name = "toDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar toDate;
    @XmlAttribute(name = "yea")
    protected String yea;
    @XmlAttribute(name = "nay")
    protected String nay;
    @XmlAttribute(name = "paired")
    protected String paired;

    /**
     * Gets the value of the vote property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vote property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Votes.Vote }
     * 
     * 
     */
    public List<Votes.Vote> getVote() {
        if (vote == null) {
            vote = new ArrayList<Votes.Vote>();
        }
        return this.vote;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSchemaVersion(Integer value) {
        this.schemaVersion = value;
    }

    /**
     * Gets the value of the parliament property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getParliament() {
        return parliament;
    }

    /**
     * Sets the value of the parliament property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setParliament(Integer value) {
        this.parliament = value;
    }

    /**
     * Gets the value of the session property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSession() {
        return session;
    }

    /**
     * Sets the value of the session property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSession(Integer value) {
        this.session = value;
    }

    /**
     * Gets the value of the sitting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSitting() {
        return sitting;
    }

    /**
     * Sets the value of the sitting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSitting(String value) {
        this.sitting = value;
    }

    /**
     * Gets the value of the votesRespecting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVotesRespecting() {
        return votesRespecting;
    }

    /**
     * Sets the value of the votesRespecting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVotesRespecting(String value) {
        this.votesRespecting = value;
    }

    /**
     * Gets the value of the fromDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFromDate() {
        return fromDate;
    }

    /**
     * Sets the value of the fromDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFromDate(XMLGregorianCalendar value) {
        this.fromDate = value;
    }

    /**
     * Gets the value of the toDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getToDate() {
        return toDate;
    }

    /**
     * Sets the value of the toDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setToDate(XMLGregorianCalendar value) {
        this.toDate = value;
    }

    /**
     * Gets the value of the yea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYea() {
        return yea;
    }

    /**
     * Sets the value of the yea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYea(String value) {
        this.yea = value;
    }

    /**
     * Gets the value of the nay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNay() {
        return nay;
    }

    /**
     * Sets the value of the nay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNay(String value) {
        this.nay = value;
    }

    /**
     * Gets the value of the paired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaired() {
        return paired;
    }

    /**
     * Sets the value of the paired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaired(String value) {
        this.paired = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="decision" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="relatedBill">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="totalYeas" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="totalNays" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="totalPaired" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *       &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="parliament" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="session" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="sitting" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="date" type="{http://www.w3.org/2001/XMLSchema}date" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "description",
        "decision",
        "relatedBill",
        "totalYeas",
        "totalNays",
        "totalPaired"
    })
    public static class Vote {

        @XmlElement(required = true)
        protected String description;
        @XmlElement(required = true)
        protected String decision;
        @XmlElement(required = true)
        protected Votes.Vote.RelatedBill relatedBill;
        protected int totalYeas;
        protected int totalNays;
        protected int totalPaired;
        @XmlAttribute(name = "number")
        protected Integer number;
        @XmlAttribute(name = "parliament")
        protected Integer parliament;
        @XmlAttribute(name = "session")
        protected Integer session;
        @XmlAttribute(name = "sitting")
        protected Integer sitting;
        @XmlAttribute(name = "date")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;

        /**
         * Gets the value of the description property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDescription() {
            return description;
        }

        /**
         * Sets the value of the description property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDescription(String value) {
            this.description = value;
        }

        /**
         * Gets the value of the decision property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDecision() {
            return decision;
        }

        /**
         * Sets the value of the decision property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDecision(String value) {
            this.decision = value;
        }

        /**
         * Gets the value of the relatedBill property.
         * 
         * @return
         *     possible object is
         *     {@link Votes.Vote.RelatedBill }
         *     
         */
        public Votes.Vote.RelatedBill getRelatedBill() {
            return relatedBill;
        }

        /**
         * Sets the value of the relatedBill property.
         * 
         * @param value
         *     allowed object is
         *     {@link Votes.Vote.RelatedBill }
         *     
         */
        public void setRelatedBill(Votes.Vote.RelatedBill value) {
            this.relatedBill = value;
        }

        /**
         * Gets the value of the totalYeas property.
         * 
         */
        public int getTotalYeas() {
            return totalYeas;
        }

        /**
         * Sets the value of the totalYeas property.
         * 
         */
        public void setTotalYeas(int value) {
            this.totalYeas = value;
        }

        /**
         * Gets the value of the totalNays property.
         * 
         */
        public int getTotalNays() {
            return totalNays;
        }

        /**
         * Sets the value of the totalNays property.
         * 
         */
        public void setTotalNays(int value) {
            this.totalNays = value;
        }

        /**
         * Gets the value of the totalPaired property.
         * 
         */
        public int getTotalPaired() {
            return totalPaired;
        }

        /**
         * Sets the value of the totalPaired property.
         * 
         */
        public void setTotalPaired(int value) {
            this.totalPaired = value;
        }

        /**
         * Gets the value of the number property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNumber() {
            return number;
        }

        /**
         * Sets the value of the number property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNumber(Integer value) {
            this.number = value;
        }

        /**
         * Gets the value of the parliament property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getParliament() {
            return parliament;
        }

        /**
         * Sets the value of the parliament property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setParliament(Integer value) {
            this.parliament = value;
        }

        /**
         * Gets the value of the session property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSession() {
            return session;
        }

        /**
         * Sets the value of the session property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSession(Integer value) {
            this.session = value;
        }

        /**
         * Gets the value of the sitting property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getSitting() {
            return sitting;
        }

        /**
         * Sets the value of the sitting property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setSitting(Integer value) {
            this.sitting = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="number" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class RelatedBill {

            @XmlAttribute(name = "number")
            protected String number;

            /**
             * Gets the value of the number property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNumber() {
                return number;
            }

            /**
             * Sets the value of the number property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNumber(String value) {
                this.number = value;
            }

        }

    }

}
